In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
dataset = pd.read_csv("kidney_disease.csv")

In [4]:
dataset

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,395,55.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,47,6700,4.9,no,no,no,good,no,no,notckd
396,396,42.0,70.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,54,7800,6.2,no,no,no,good,no,no,notckd
397,397,12.0,80.0,1.020,0.0,0.0,normal,normal,notpresent,notpresent,...,49,6600,5.4,no,no,no,good,no,no,notckd
398,398,17.0,60.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,51,7200,5.9,no,no,no,good,no,no,notckd
399,399,58.0,80.0,1.025,0.0,0.0,normal,normal,notpresent,notpresent,...,53,6800,6.1,no,no,no,good,no,no,notckd

In [5]:
dataset.isna().sum()

id                  0
age                 9
bp                 12
sg                 47
al                 46
su                 49
rbc               152
pc                 65
pcc                 4
ba                  4
bgr                44
bu                 19
sc                 17
sod                87
pot                88
hemo               52
pcv                70
wc                105
rc                130
htn                 2
dm                  2
cad                 2
appet               1
pe                  1
ane                 1
classification      0
dtype: int64

In [6]:
dataset.info

<bound method DataFrame.info of       id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent
1      1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent
..   ...   ...   ...    ...  ...  ...     ...       ...         ...
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no
1    notpresent  ...   38  6000  NaN   no   no   no  good   no   no
2    notpresent  ...   31  7500  NaN   no  yes   no  poor   no  yes
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no

    classification
0              ckd
1              ckd
2              ckd
3              ckd
4              ckd
..             ...
395         notckd
396         notckd
397         notckd
398         notckd
399         notckd

[400 rows x 26 columns]>

In [7]:
dataset.isnull

<bound method DataFrame.isnull of       id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent
1      1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent
..   ...   ...   ...    ...  ...  ...     ...       ...         ...
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no
1    notpresent  ...   38  6000  NaN   no   no   no  good   no   no
2    notpresent  ...   31  7500  NaN   no  yes   no  poor   no  yes
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no

    classification
0              ckd
1              ckd
2              ckd
3              ckd
4              ckd
..             ...
395         notckd
396         notckd
397         notckd
398         notckd
399         notckd

[400 rows x 26 columns]>

In [8]:
dataset.isnull()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,False,False,False,False,False,False,True,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,True,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
396,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
397,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
398,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
399,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [9]:
dataset.columns

Index(['id', 'age', 'bp', 'sg', 'al', 'su', 'rbc', 'pc', 'pcc', 'ba', 'bgr',
       'bu', 'sc', 'sod', 'pot', 'hemo', 'pcv', 'wc', 'rc', 'htn', 'dm', 'cad',
       'appet', 'pe', 'ane', 'classification'],
      dtype='object')

In [10]:
dataset["appet"]=dataset["appet"].fillna(dataset["appet"].mode()[0])

NameError: name 'dataset' is not defined

In [11]:
dataset["appet"].isna().sum()

np.int64(0)

In [12]:
dataset["pe"].isna().sum()

np.int64(1)

In [13]:
dataset["pe"]=dataset["pe"].fillna(dataset["pe"].mode()[0])

In [14]:
dataset["pe"].isna().sum()

np.int64(0)

In [15]:
dataset["ane"].isna().sum()

np.int64(1)

In [16]:
dataset["ane"]=dataset["ane"].fillna(dataset["ane"].mode()[0])

In [17]:
dataset["ane"].isna().sum()

np.int64(0)

In [18]:
dataset["cad"].isna().sum()

np.int64(2)

In [19]:
dataset["cad"]=dataset["cad"].fillna(dataset["cad"].mode()[0])

In [20]:
dataset["cad"].isna().sum()

np.int64(0)

In [21]:
dataset["dm"].isna().sum()

np.int64(2)

In [22]:
dataset["dm"]=dataset["dm"].fillna(dataset["dm"].mode()[0])

In [23]:
dataset["dm"].isna().sum()

np.int64(0)

In [24]:
dataset["htn"].isna().sum()

np.int64(2)

In [25]:
dataset["htn"]=dataset["htn"].fillna(dataset["htn"].mode()[0])

In [26]:
dataset["htn"].isna().sum()

np.int64(0)

In [27]:
dataset["rc"].isna().sum()

np.int64(130)

In [28]:
print(dataset["rc"].dtype)
print(dataset["rc"].unique())

object
['5.2' nan '3.9' '4.6' '4.4' '5' '4.0' '3.7' '3.8' '3.4' '2.6' '2.8' '4.3'
 '3.2' '3.6' '4' '4.1' '4.9' '2.5' '4.2' '4.5' '3.1' '4.7' '3.5' '6.0'
 '5.0' '2.1' '5.6' '2.3' '2.9' '2.7' '8.0' '3.3' '3.0' '3' '2.4' '4.8'
 '\t?' '5.4' '6.1' '6.2' '6.3' '5.1' '5.8' '5.5' '5.3' '6.4' '5.7' '5.9'
 '6.5']

In [29]:
# Remove leading/trailing spaces and tabs
dataset["rc"] = dataset["rc"].astype(str).str.strip()

# Replace '?' with NaN
dataset["rc"] = dataset["rc"].replace("?", np.nan)

# Convert to numeric
dataset["rc"] = pd.to_numeric(dataset["rc"], errors="coerce")

# Fill missing values with the median
dataset["rc"] = dataset["rc"].fillna(dataset["rc"].median())

In [30]:
dataset["rc"].isna().sum()

np.int64(0)

In [31]:
dataset["rc"].dtype

dtype('float64')

In [32]:
dataset["wc"].isna().sum()

np.int64(105)

In [33]:
print(dataset["wc"].dtype)
print(dataset["wc"].unique())

object
['7800' '6000' '7500' '6700' '7300' nan '6900' '9600' '12100' '4500'
 '12200' '11000' '3800' '11400' '5300' '9200' '6200' '8300' '8400' '10300'
 '9800' '9100' '7900' '6400' '8600' '18900' '21600' '4300' '8500' '11300'
 '7200' '7700' '14600' '6300' '\t6200' '7100' '11800' '9400' '5500' '5800'
 '13200' '12500' '5600' '7000' '11900' '10400' '10700' '12700' '6800'
 '6500' '13600' '10200' '9000' '14900' '8200' '15200' '5000' '16300'
 '12400' '\t8400' '10500' '4200' '4700' '10900' '8100' '9500' '2200'
 '12800' '11200' '19100' '\t?' '12300' '16700' '2600' '26400' '8800'
 '7400' '4900' '8000' '12000' '15700' '4100' '5700' '11500' '5400' '10800'
 '9900' '5200' '5900' '9300' '9700' '5100' '6600']

In [34]:
import numpy as np
import pandas as pd

# Remove leading/trailing spaces and tab characters
dataset["wc"] = dataset["wc"].astype(str).str.strip()

# Replace '?' with NaN
dataset["wc"] = dataset["wc"].replace("?", np.nan)

# Convert to numeric
dataset["wc"] = pd.to_numeric(dataset["wc"], errors="coerce")

# Fill missing values with the median
dataset["wc"] = dataset["wc"].fillna(dataset["wc"].median())

In [35]:
dataset["wc"].isna().sum()

np.int64(0)

In [36]:
dataset["pcv"].isna().sum()

np.int64(70)

In [37]:
print(dataset["pcv"].dtype)
print(dataset["pcv"].unique())

object
['44' '38' '31' '32' '35' '39' '36' '33' '29' '28' nan '16' '24' '37' '30'
 '34' '40' '45' '27' '48' '\t?' '52' '14' '22' '18' '42' '17' '46' '23'
 '19' '25' '41' '26' '15' '21' '43' '20' '\t43' '47' '9' '49' '50' '53'
 '51' '54']

In [38]:
# Remove leading/trailing spaces and tab characters
dataset["wc"] = dataset["wc"].astype(str).str.strip()

# Replace '?' with NaN
dataset["wc"] = dataset["wc"].replace("?", np.nan)

# Convert to numeric
dataset["wc"] = pd.to_numeric(dataset["wc"], errors="coerce")

# Fill missing values with the median
dataset["wc"] = dataset["wc"].fillna(dataset["wc"].median())

In [39]:
dataset["wc"].isna().sum()

np.int64(0)

In [40]:
dataset["hemo"].isna().sum()

np.int64(52)

In [41]:
dataset["hemo"].dtype

dtype('float64')

In [42]:
dataset["hemo"] = dataset["hemo"].fillna(dataset["hemo"].median())

In [43]:
dataset["hemo"].isna().sum()

np.int64(0)

In [44]:
dataset["pot"].isna().sum()

np.int64(88)

In [45]:
dataset["pot"] = dataset["pot"].fillna(dataset["pot"].median())

In [46]:
dataset["pot"].isna().sum()

np.int64(0)

In [47]:
dataset["sod"].isna().sum()

np.int64(87)

In [48]:
dataset["pot"] = dataset["pot"].fillna(dataset["pot"].median())

In [49]:
dataset["sc"].isna().sum()

np.int64(17)

In [50]:
dataset["sc"] = dataset["sc"].fillna(dataset["sc"].median())

In [51]:
dataset["sc"].isna().sum()

np.int64(0)

In [52]:
dataset["sod"].isna().sum()

np.int64(87)

In [53]:
dataset["sod"] = dataset["sod"].fillna(dataset["sod"].median())

In [54]:
dataset["sod"].isna().sum()

np.int64(0)

In [55]:
dataset["bu"].isna().sum()

np.int64(19)

In [56]:
dataset["bu"] = dataset["bu"].fillna(dataset["bu"].median())

In [57]:
dataset["bu"].isna().sum()

np.int64(0)

In [58]:
dataset["bgr"].isna().sum()

np.int64(44)

In [59]:
dataset["bgr"] = dataset["bgr"].fillna(dataset["bgr"].median())

In [60]:
dataset["bgr"].isna().sum()

np.int64(0)

In [61]:
dataset["bgr"].isna().sum()

np.int64(0)

In [62]:
dataset["ba"] = dataset["ba"].fillna(dataset["ba"].mode()[0])

In [63]:
dataset["ba"].isna().sum()

np.int64(0)

In [64]:
dataset["pcc"].isna().sum()

np.int64(4)

In [65]:
dataset["pcc"] = dataset["pcc"].fillna(dataset["pcc"].mode()[0])

In [66]:
dataset["pcc"].isna().sum()

np.int64(0)

In [67]:
dataset["pc"].isna().sum()

np.int64(65)

In [68]:
dataset["pc"] = dataset["pc"].fillna(dataset["pc"].mode()[0])

In [69]:
dataset["pc"].isna().sum()

np.int64(0)

In [70]:
dataset["rbc"].isna().sum()

np.int64(152)

In [71]:
dataset["rbc"] = dataset["rbc"].fillna(dataset["rbc"].mode()[0])

In [72]:
dataset["rbc"].isna().sum()

np.int64(0)

In [73]:
dataset["su"].isna().sum()

np.int64(49)

In [74]:
dataset["su"].unique

<bound method Series.unique of 0      0.0
1      0.0
2      3.0
3      0.0
4      0.0
      ...
395    0.0
396    0.0
397    0.0
398    0.0
399    0.0
Name: su, Length: 400, dtype: float64>

In [75]:
dataset["su"] = dataset["su"].fillna(0)

In [76]:
dataset["su"].isna().sum()

np.int64(0)

In [77]:
dataset["al"].isna().sum()

np.int64(46)

In [78]:
dataset["al"] = dataset["al"].fillna(0)

In [79]:
dataset["al"].isna().sum()

np.int64(0)

In [80]:
dataset["sg"].isna().sum()

np.int64(47)

In [81]:
dataset["sg"] = dataset["sg"].fillna(dataset["sg"].median())

In [82]:
dataset["sg"].isna().sum()

np.int64(0)

In [83]:
dataset["bp"].isna().sum()

np.int64(12)

In [84]:
dataset["bp"] = dataset["bp"].fillna(dataset["bp"].median())

In [85]:
dataset["bp"].isna().sum()

np.int64(0)

In [86]:
dataset["age"].isna().sum()

np.int64(9)

In [87]:
dataset["age"] = dataset["age"].fillna(dataset["age"].median())

In [88]:
dataset["age"].isna().sum()

np.int64(0)