In [1]:
from module1 import class1

In [2]:
import pandas as pd

In [3]:
dataset = pd.read_csv("Placement.csv")

In [4]:
quan,qual=class1.quanQual(dataset)

In [5]:
quan

['sl_no', 'ssc_p', 'hsc_p', 'degree_p', 'etest_p', 'mba_p', 'salary']

# Measure of Central Tendency

In [6]:
descriptive = pd.DataFrame(index=["Mean","Median","Mode"],columns=quan)

In [7]:
descriptive

       sl_no ssc_p hsc_p degree_p etest_p mba_p salary
Mean     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Median   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode     NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [8]:
for columnName in quan:
    descriptive.loc["Mean", columnName] = dataset[columnName].mean()
    descriptive.loc["Median", columnName] = dataset[columnName].median()
    descriptive.loc["Mode", columnName] = dataset[columnName].mode()[0]

In [9]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
Mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
Median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0

#  Measure of location of Data

In [10]:

descriptive = pd.DataFrame(index=["mean","median","Mode","Q1:25%","Q2:50%", "Q3:75%","Q4:100%","IQR","1.5 Rule","Greater","Lesser","kurtosis","skew","var","min","max"],columns=quan)

In [11]:
descriptive

         sl_no ssc_p hsc_p degree_p etest_p mba_p salary
mean       NaN   NaN   NaN      NaN     NaN   NaN    NaN
median     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Mode       NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q1:25%     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q2:50%     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q3:75%     NaN   NaN   NaN      NaN     NaN   NaN    NaN
Q4:100%    NaN   NaN   NaN      NaN     NaN   NaN    NaN
IQR        NaN   NaN   NaN      NaN     NaN   NaN    NaN
1.5 Rule   NaN   NaN   NaN      NaN     NaN   NaN    NaN
Greater    NaN   NaN   NaN      NaN     NaN   NaN    NaN
Lesser     NaN   NaN   NaN      NaN     NaN   NaN    NaN
kurtosis   NaN   NaN   NaN      NaN     NaN   NaN    NaN
skew       NaN   NaN   NaN      NaN     NaN   NaN    NaN
var        NaN   NaN   NaN      NaN     NaN   NaN    NaN
min        NaN   NaN   NaN      NaN     NaN   NaN    NaN
max        NaN   NaN   NaN      NaN     NaN   NaN    NaN

In [12]:
for cname in quan:
    descriptive.loc["mean", cname] = dataset[cname].mean()
    descriptive.loc["median", cname] = dataset[cname].median()
    descriptive.loc["Mode", cname] = dataset[cname].mode()[0]

    descriptive.loc["Q1:25%", cname] = dataset[cname].quantile(0.25)
    descriptive.loc["Q2:50%", cname] = dataset[cname].quantile(0.50)
    descriptive.loc["Q3:75%", cname] = dataset[cname].quantile(0.75)
    descriptive.loc["Q4:100%", cname] = dataset[cname].max()

    descriptive.loc["IQR", cname] = (
        descriptive.loc["Q3:75%", cname] -
        descriptive.loc["Q1:25%", cname]
    )

    descriptive.loc["1.5 Rule", cname] = (
        1.5 * descriptive.loc["IQR", cname]
    )

    descriptive.loc["Greater", cname] = (
        descriptive.loc["Q3:75%", cname] +
        descriptive.loc["1.5 Rule", cname]
    )

    descriptive.loc["Lesser", cname] = (
        descriptive.loc["Q1:25%", cname] -
        descriptive.loc["1.5 Rule", cname]
    )

    descriptive.loc["kurtosis", cname] = dataset[cname].kurt()
    descriptive.loc["skew", cname] = dataset[cname].skew()
    descriptive.loc["var", cname] = dataset[cname].var()
    descriptive.loc["min", cname] = dataset[cname].min()
    descriptive.loc["max", cname] = dataset[cname].max()

In [13]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5 Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
kurtosis,-1.2,-0.60751,0.450765,0.052143,-1.08858,-0.470723,18.544273
skew,0.0,-0.132649,0.163639,0.244917,0.282308,0.313576,3.569747
var,3870.0,117.228377,118.755706,54.151103,176.251018,34.028376,8734295412.759695
min,1,40.89,37.0,50.0,50.0,51.21,200000.0
max,215,89.4,97.7,91.0,98.0,77.89,940000.0

In [14]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5 Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
kurtosis,-1.2,-0.60751,0.450765,0.052143,-1.08858,-0.470723,18.544273
skew,0.0,-0.132649,0.163639,0.244917,0.282308,0.313576,3.569747
var,3870.0,117.228377,118.755706,54.151103,176.251018,34.028376,8734295412.759695
min,1,40.89,37.0,50.0,50.0,51.21,200000.0
max,215,89.4,97.7,91.0,98.0,77.89,940000.0

In [15]:
lesser =[]
greater=[]

In [16]:
for cname in quan:
    if descriptive.loc["min", cname] < descriptive.loc["Lesser", cname]:
        lesser.append(cname)

    if descriptive.loc["max", cname] > descriptive.loc["Greater", cname]:
        greater.append(cname)

In [17]:
for cname in lesser:
    dataset.loc[
        dataset[cname] < descriptive.loc["Lesser", cname],
        cname
    ] = descriptive.loc["Lesser", cname]

for cname in greater:
    dataset.loc[
        dataset[cname] > descriptive.loc["Greater", cname],
        cname
    ] = descriptive.loc["Greater", cname]

# Replacing Outlier with IQR

In [18]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5 Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
kurtosis,-1.2,-0.60751,0.450765,0.052143,-1.08858,-0.470723,18.544273
skew,0.0,-0.132649,0.163639,0.244917,0.282308,0.313576,3.569747
var,3870.0,117.228377,118.755706,54.151103,176.251018,34.028376,8734295412.759695
min,1,40.89,37.0,50.0,50.0,51.21,200000.0
max,215,89.4,97.7,91.0,98.0,77.89,940000.0

In [19]:
lesser

['hsc_p']

In [20]:
greater

['hsc_p', 'degree_p', 'salary']

In [21]:
descriptive

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
Q4:100%,215,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5 Rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
Greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
Lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
kurtosis,-1.2,-0.60751,0.450765,0.052143,-1.08858,-0.470723,18.544273
skew,0.0,-0.132649,0.163639,0.244917,0.282308,0.313576,3.569747
var,3870.0,117.228377,118.755706,54.151103,176.251018,34.028376,8734295412.759695
min,1,40.89,37.0,50.0,50.0,51.21,200000.0
max,215,89.4,97.7,91.0,98.0,77.89,940000.0